services:
  cleverloon:
    image: cleverloon
    ports:
      - "80:80"
      - "443:443"
    build:
      context: .
      args:
        nginx_conf: nginx.conf
      dockerfile: ./Dockerfile
  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"  # Renew certificates every 12 hours
